# Generated by Django 3.0.4 on 2020-03-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_myuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
