# Generated by Django 3.0.4 on 2020-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20200305_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='first name'),
        ),
    ]
