# Generated by Django 3.0.4 on 2020-03-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20200305_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Is email verified'),
        ),
    ]
