# Generated by Django 3.0.4 on 2020-03-11 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest.enums


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_myuser_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[(rest.enums.TokenType['EMAIL_VERIFICATION'], 'EMAIL VERIFICATION')], max_length=100)),
                ('token', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='create date')),
                ('expiry_minutes', models.IntegerField(default=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Token',
            },
        ),
    ]
