# Generated by Django 3.0.4 on 2020-03-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('Description', models.CharField(default='', max_length=555)),
                ('created_post', models.DateField(null=True)),
            ],
        ),
    ]
