# Generated by Django 3.0.4 on 2020-03-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_post_userr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Description',
            new_name='description',
        ),
    ]
