# Generated by Django 3.0.4 on 2020-03-11 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20200311_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userr',
        ),
    ]
