# Generated by Django 3.0.4 on 2020-03-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
